### ISSUE TITLE
Bigfont parse  failed

### ISSUE THREAD

**Issue by ironresolve** [tatarize/shxparser#1]
i need  chinese font parse   witch is  bigfont 
i have tried  your  project    but  failed

**Comment by tatarize** [comment]
0.0.2 is released. It might have some better luck. I did some corrections to some parsing especially with regard to names of shapes within the file. If that still fails you can send me the file at tatarize@gmail.com and I can try to diagnose the problem more fully. There are apparently still some fonts that won't parse. However all the major errors will give ShxParseErrors rather than fail more generally.

**Comment by ironresolve** [comment]
hello my friend  long time no see
because i am  chinese ,  so  login  out internet  is not so easy  .
beside   im not expect  you can answer me    haha  
a years ago , not long  after i ask that question,  i figure it out  myself ,i fogot  to tell you  here on github.   haha   sorry  
i use  C/C++ /QT   your project  is  python    so a years ago  i  met a lot  of problems....
now  it works  very well    
thank you  very  mush  !!!
